name: application_voyage
description: "A new Flutter project."
publish_to: 'none' # Supprime cette ligne si tu veux publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #  Réseau et stockage
  http: ^0.13.6
  shared_preferences: ^2.2.3

  # Pour utiliser Google Fonts
  google_fonts: ^4.0.4

  # Pour les composants déjà stylés (boutons, cards, chips, etc.)
  getwidget: ^4.0.0

  # Gestion d'état
  provider: ^6.1.2

  # WebView et ouverture de liens externes
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.0  #  Ajout du package manquant

  # Icônes et formatage
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/photos.jpg
    - assets/logo-event.png
    - assets/google.png
    - assets/cadeau.png
    - assets/cadeau1.png
    - assets/apple.png
    - assets/heberg.png
    - assets/hebergement.png
    - assets/bienvenu.png
    - assets/contact.png
    - assets/facebook.png
    - assets/concert.png
